name: Loki IOC Scan

on:
  workflow_dispatch:

jobs:
  loki-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yara libyara-dev python3-pip

    - name: Clone Loki scanner repository
      run: git clone https://github.com/Neo23x0/Loki.git

    - name: Clone signature-base repository
      run: git clone https://github.com/Neo23x0/signature-base.git

    - name: Link signatures into Loki
      run: ln -s ${{ github.workspace }}/signature-base ${{ github.workspace }}/Loki/signatures

    - name: Install Loki Python dependencies
      working-directory: ./Loki
      run: |
        pip install -r requirements.txt
        chmod +x loki.py

    - name: Run Loki scan with custom IOCs
      working-directory: ./Loki
      run: |
        ./loki.py --all --intense --csv --onlyrelevant --debug \
          --signature ../custom-iocs --signature ./signatures
